### ISSUE TITLE
建议字体库增加个思源黑体，这个苹方体符号好像不太全，有些不显示

### ISSUE THREAD

**Issue by atriatri20** [FloatTech/zbputils#27]
![image](https://user-images.githubusercontent.com/21164819/228020762-3d95eae8-beda-404f-84a8-82553770629d.png)

**Comment by fumiama** [comment]
你可以向 https://github.com/FloatTech/zbpdata 的Font文件夹PR，记得遵守格式。接下来你需要向 https://github.com/FloatTech/zbputils 的 img/text/font.go PR，将新增字体按格式加在末尾。
