### ISSUE TITLE
[Feat] 有关插件控制的建议

### ISSUE THREAD

**Issue by EatHatsuneShallots** [FloatTech/zbputils#41]
# 有关响应和沉默命令的建议
目前 /响应 、/沉默、 /全局响应 和 /全局沉默 不能还原，希望能添加 /还原响应 和 /还原全局响应 的命令

# 希望能添加 /禁止群聊 和 /允许群聊 命令
虽然这两个命令 /此处启用全部插件 和 /此处禁用全部插件 可以办到，但是不会对后面新增的插件生效，且需要在目标群发送，不过嘛
估计要动底层 [zbpctrl](https://github.com/FloatTech/zbpctrl) 的 ~~屎山~~ 代码才能实现（

# 可以让超级管理员控制若干个用户，以及若干个群聊的响应状态
命令：
/沉默用户 xxx xxx
/沉默群聊 xxx xxx

**Comment by fumiama** [comment]
> 希望能添加 /还原响应 和 /还原全局响应 的命令

沉默就是还原响应。全局沉默实际就是还原全局响应。

> 希望能添加 /禁止群聊 和 /允许群聊 命令

你可能在找：沉默

> 可以让超级管理员控制若干个用户，以及若干个群聊的响应状态

你可能在找：封禁、禁止

**Comment by EatHatsuneShallots** [comment]
> 你可能在找：沉默

不能指定群聊，而且群管理员可以重新使用 /响应 恢复

> 你可能在找：封禁、禁止

“封禁” 只能封禁用户，“禁止” 只能禁止用户使用某个插件，一样不能指定群聊，且能被群管理员使用 /允许 恢复

**NOTE: 我请求的这些指令都是给超级管理员用的**

**Comment by fumiama** [comment]
> 不能指定群聊，而且群管理员可以重新使用 /响应 恢复

建议直接退出群聊。

> “封禁” 只能封禁用户，“禁止” 只能禁止用户使用某个插件，一样不能指定群聊，且能被群管理员使用 /允许 恢复

如果不信任那个群的管理，建议不要在该群提供服务。机器人哪天没的都不知道。管理员具有禁言权限，因而可以控制机器人的响应是合理的。
